from typing import Any
from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    Response returned by chat API.
    """

    answer: str = Field(
        ...,
        description="Final response generated by the AI assistant"
    )



def extract_response_text(content: Any) -> str:
    """
    Convert LangChain AIMessage content into plain text.
    """

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        texts = []

        for block in content: # type: ignore
            if isinstance(block, dict):
                text = block.get("text") # type: ignore

                if text:
                    texts.append(text) # type: ignore

        return "\n".join(texts) # type: ignore

    return str(content)