from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """
    Response returned by chat API.
    """

    answer: str = Field(
        ...,
        description="Final response generated by the AI assistant"
    )