"""
This type stub file was generated by pyright.
"""

from langgraph.stream._types import ProtocolEvent
from langgraph.types import StreamPart

def convert_to_protocol_event(part: StreamPart) -> ProtocolEvent:
    """Convert a v2 StreamPart to a ProtocolEvent.

    Args:
        part: A stream part with keys `type`, `ns`, `data`, and
            optionally `interrupts` (present on values events).

    Returns:
        The equivalent ProtocolEvent.
    """
    ...

