"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from langgraph.stream._types import ProtocolEvent, StreamTransformer

TransformerFactory = Callable[["tuple[str, ...]"], StreamTransformer]
class StreamMux:
    """Central event dispatcher for the streaming infrastructure.

    Owns the main event log and routes events through a transformer
    pipeline. StreamChannels with a name discovered in transformer
    projections are auto-wired so that every `push()` also injects a
    `ProtocolEvent` into the main log. StreamChannels without a name
    are local-only.

    Pass `is_async=True` when the mux will be consumed via async
    iteration (`handler.astream()`). All StreamChannel instances
    discovered during registration are automatically bound to the
    matching mode.

    Attributes:
        extensions: Merged projection dict across all registered
            transformers. Treat as read-only — mutations won't be
            reflected back in individual transformers' state.
        native_keys: Projection keys contributed by transformers with
            `_native = True`.
    """
    def __init__(self, transformers: list[StreamTransformer] | None = ..., *, is_async: bool = ..., factories: list[TransformerFactory] | None = ..., scope: tuple[str, ...] = ..., _assign_seq: bool = ...) -> None:
        """Initialize the mux and register transformers in order.

        Callers pass either `transformers` (pre-built instances) or
        `factories` (callables producing fresh instances per mux). Each
        transformer's `init()` is called, projections are merged into
        `extensions`, `_native` keys are recorded in `native_keys`, and
        any StreamChannel instances are bound and (if named) wired.

        Transformers with `StreamTransformer.before_builtins = True` are
        registered ahead of the rest, preserving relative order within
        each lane. This lets content-mutating transformers (PII
        redaction, content filters, etc.) run before built-ins like
        `MessagesTransformer` that eagerly snapshot text fields into
        their projections. See `StreamTransformer.before_builtins` for
        the contract and foot-guns.

        Args:
            transformers: Already-built transformer instances. Registered
                only on this mux — they are NOT cloned into child
                mini-muxes built by `_make_child`. Use `factories` for
                transformers that should propagate to nested scopes.
            is_async: True for async dispatch (`apush` / `aclose` /
                `afail`), False for the sync path.
            factories: One-argument callables `(scope) -> StreamTransformer`.
                Called once with this mux's `scope` here, and cloned
                again per child scope by `_make_child` so each
                sub-mux gets fresh instances.
            scope: The namespace the mux operates within. The root mux
                is `()`.
            _assign_seq: Internal flag for child muxes. Root muxes assign
                monotonic `seq` numbers when appending to their main event
                log; child muxes share forwarded event objects and must not
                mutate their envelopes.

        Raises:
            RuntimeError: If any transformer requires an async run but
                the mux is in sync mode.
            TypeError: If a transformer's `init()` doesn't return a dict.
            ValueError: If transformers' projection keys collide.
        """
        ...
    
    def transformer_by_key(self, key: str) -> StreamTransformer | None:
        """Return the transformer that contributed `key` to the projection."""
        ...
    
    def bind_pump(self, fn: Callable[[], bool]) -> None:
        """Wire the sync pull callback onto every projection in this mux.

        Records the pump on the mux so child mini-muxes built by
        `_make_child` can inherit it. Propagates to:
        - the main event log (`self._events`)
        - every projection StreamChannel in `extensions`
        - any registered transformer that exposes `_bind_pump` (e.g.
          `MessagesTransformer` so `ChatModelStream` instances drive the
          shared pump from their cursors)
        """
        ...
    
    def bind_apump(self, fn: Callable[[], Awaitable[bool]]) -> None:
        """Async counterpart to `bind_pump`."""
        ...
    
    def push(self, event: ProtocolEvent) -> None:
        """Route an event through all transformers, then append to the main log.

        Each transformer's `process()` is called in registration order.
        If any transformer returns False, the event is suppressed from
        the main log, but transformers that already saw it keep their
        side effects.

        On the root mux, `seq` is assigned right before an event enters
        the main log, not before the transformer pipeline runs. This
        ensures that events auto-forwarded from StreamChannels during
        `process()` get earlier seq numbers than the original event,
        preserving monotonic ordering in the root log. Child muxes do
        not assign `seq`, so subgraph forwarding can share event objects
        without mutating their envelopes.

        Args:
            event: The protocol event to dispatch.
        """
        ...
    
    def close(self) -> None:
        """Finalize all transformers, close all projections and the main log.

        StreamChannels discovered in transformer projections are
        auto-closed after `finalize()` runs — transformers don't need
        to close them manually. If any transformer's `finalize()` raises,
        the remaining transformers, projections, and the main log are
        still closed; the first error is re-raised after cleanup
        completes.

        Raises:
            BaseException: The first error raised by a transformer's
                `finalize()`, re-raised after cleanup finishes.
        """
        ...
    
    def fail(self, err: BaseException) -> None:
        """Fail all transformers, projections, and the main log.

        StreamChannels discovered in transformer projections are
        auto-failed — transformers don't need to fail them manually.
        If any transformer's `fail()` raises, the remaining
        transformers, projections, and the main log are still failed.

        Args:
            err: The exception that ended the run.
        """
        ...
    
    async def apush(self, event: ProtocolEvent) -> None:
        """Dispatch an event on the async lane.

        Awaits each transformer's `aprocess` in registration order
        before appending to the main log. A slow `aprocess` serializes
        the pipeline by design — that's the guarantee that lets a later
        transformer (or a synchronous consumer) see the result of the
        async work. For decoupled work, use `schedule()` from inside
        `process` / `aprocess` instead.

        The main log append is a non-blocking `push` — matching v1's
        `put_nowait` shape. The root mux assigns `seq`; child muxes do
        not, so forwarded subgraph events can be shared without copying.
        Memory is bounded by caller pace via the caller-driven pump; see
        `StreamChannel` for the full tradeoff story.

        Args:
            event: The protocol event to dispatch.
        """
        ...
    
    async def aclose(self) -> None:
        """Finalize on the async lane.

        Awaits every task started via `StreamTransformer.schedule()`
        across all transformers, then calls `afinalize()` on each,
        then auto-closes channels and the main event log.

        If any scheduled task raised under `on_error="raise"`, or any
        transformer's `afinalize` raises, the exception propagates.
        The caller (the pump) handles it by routing into `afail`.

        Raises:
            BaseException: The first scheduled-task or `afinalize`
                error, re-raised after cleanup.
        """
        ...
    
    async def afail(self, err: BaseException) -> None:
        """Fail on the async lane.

        Cancels every scheduled task across all transformers, awaits
        them to completion, then runs each transformer's `afail` hook
        and auto-fails channels and the main event log.

        Args:
            err: The exception that ended the run.
        """
        ...
    


