"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Iterator
from types import TracebackType
from typing import Any, TYPE_CHECKING
from langchain_core._api import beta
from langgraph.stream._mux import StreamMux
from langgraph.stream._types import ProtocolEvent
from langgraph.stream.transformers import SubgraphStatus

if TYPE_CHECKING:
    ...
@beta(message="The v3 streaming protocol on Pregel is experimental.")
class GraphRunStream:
    """Sync run stream with caller-driven pumping.

    The caller's iteration on any projection (`values`, `messages`,
    raw events, or `output`) drives the graph forward. No background
    thread is used — the caller's `for` loop is the pump.

    Projections are single-consumer — iterating `run.values` twice
    raises. Use `projection.tee(n)` if you genuinely need fan-out.

    All transformer projections live in `extensions`. Native transformer
    projections (those with `_native = True`) are also set as direct
    attributes on this instance (e.g. `run.values`, `run.messages`).

    !!! warning

        Returned by `Pregel.stream_events(version="v3")`, which is
        experimental and may change.
    """
    def __init__(self, graph_iter: Iterator[Any] | None, mux: StreamMux, *, wire_pump: bool = ...) -> None:
        """Initialize the run stream.

        Args:
            graph_iter: Pull-based iterator over the graph's stream,
                or `None` for nested run streams whose pump is driven
                by an outer run (e.g. `SubgraphRunStream`).
            mux: The StreamMux owning projections and the main log.
            wire_pump: When True (default), bind `_pump_next` as the
                mux's pump callable. Subclasses that inherit a parent
                pump via `StreamMux._make_child` should pass False to
                preserve the parent binding.
        """
        ...
    
    def abort(self) -> None:
        """Stop the run early.

        Closes the underlying graph iterator (propagating `GeneratorExit`
        so in-flight nodes and subgraphs are cancelled), closes the mux,
        and marks the stream exhausted. Idempotent.
        """
        ...
    
    def __enter__(self) -> GraphRunStream:
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None) -> None:
        ...
    
    @property
    def output(self) -> dict[str, Any] | None:
        """Drive the run to completion and return the final state."""
        ...
    
    @property
    def interrupted(self) -> bool:
        """Drive the run to completion, then return whether it was
        interrupted.

        Raises:
            BaseException: If the run ended with an error.
        """
        ...
    
    @property
    def interrupts(self) -> list[Any]:
        """Drive the run to completion, then return interrupt payloads.

        Raises:
            BaseException: If the run ended with an error.
        """
        ...
    
    def __iter__(self) -> Iterator[ProtocolEvent]:
        """Subscribe to the main event log and iterate protocol events."""
        ...
    
    def interleave(self, *names: str) -> Iterator[tuple[str, Any]]:
        """Iterate multiple projections in arrival order, yielding ``(name, item)``.

        Items are ordered by a monotonic push stamp assigned when each
        transformer pushes into its `StreamChannel`. This gives strict
        arrival ordering across projections, unlike round-robin.

        Args:
            *names: Projection keys to interleave. Must match keys in
                ``extensions``.

        Yields:
            ``(name, item)`` tuples in arrival order across the named
            projections.

        Each named channel is locked for the duration of iteration and
        released when the generator completes, is closed, or raises.
        Channels cannot be subscribed concurrently — use `.tee(n)` if
        you need fan-out.

        Raises:
            KeyError: If a name doesn't match a registered projection.

        Example:
            ```python
            for name, item in run.interleave("messages", "values"):
                if name == "messages":
                    print("msg:", item)
                else:
                    print("val:", item)
            ```
        """
        ...
    


@beta(message="The v3 streaming protocol on Pregel is experimental.")
class AsyncGraphRunStream:
    """Async run stream with caller-driven pumping.

    Async iteration on any projection drives the graph forward — there
    is no background task. Concurrent consumers share a single-flight
    pump via an `asyncio.Lock`, so each awaiting cursor contributes one
    event per acquisition. Backpressure comes from the logs: when a
    subscribed log's buffer reaches `maxlen`, `apush` awaits the
    subscriber to drain, which holds back the pump and paces the graph.

    Projections are single-consumer — a second `aiter(run.values)`
    raises. Use `projection.tee(n)` for fan-out.

    Use as an async context manager to guarantee clean shutdown on
    early exit:

    ```python
    async with await handler.astream(input) as run:
        async for msg in run.messages:
            ...
    ```

    !!! warning

        Awaited from `Pregel.astream_events(version="v3")`, which is
        experimental and may change.
    """
    def __init__(self, graph_aiter: AsyncIterator[Any] | None, mux: StreamMux, *, wire_pump: bool = ...) -> None:
        """Initialize the async run stream.

        Args:
            graph_aiter: Async iterator over the graph's stream, or
                `None` for nested run streams whose pump is driven by
                an outer run (e.g. `AsyncSubgraphRunStream`).
            mux: The StreamMux owning projections and the main log.
            wire_pump: When True (default), bind `_apump_next` as the
                mux's async pump callable. Subclasses that inherit a
                parent pump via `StreamMux._make_child` should pass
                False to preserve the parent binding.
        """
        ...
    
    async def abort(self) -> None:
        """Stop the run early.

        Marks the stream exhausted and wakes any pump-waiters. Cancels an
        in-flight pull if one is running, then closes the underlying graph
        iterator, so running nodes and nested subgraphs are cancelled
        whether or not a pump is mid-pull. Closes the mux; any `apush`
        blocked on backpressure wakes and returns without appending.
        Idempotent.
        """
        ...
    
    async def __aenter__(self) -> AsyncGraphRunStream:
        ...
    
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None) -> None:
        ...
    
    async def output(self) -> dict[str, Any] | None:
        """Drive the run to completion and return the final state.

        Methods (not properties) on the async lane so `run.output`
        without `await` raises at type-check time instead of silently
        yielding a coroutine object.

        Example:
            ```python
            output = await run.output()
            ```

        Raises:
            BaseException: If the run ended with an error.
        """
        ...
    
    async def interrupted(self) -> bool:
        """Drive the run to completion and return whether it was
        interrupted.

        Raises:
            BaseException: If the run ended with an error.
        """
        ...
    
    async def interrupts(self) -> list[Any]:
        """Drive the run to completion and return interrupt payloads.

        Raises:
            BaseException: If the run ended with an error.
        """
        ...
    
    def __aiter__(self) -> AsyncIterator[ProtocolEvent]:
        """Subscribe to the main event log and iterate protocol events."""
        ...
    


class _SubgraphRunStreamMixin:
    """Subgraph metadata + parent-pump delegation shared by both lanes.

    Inherits from `GraphRunStream` (or `AsyncGraphRunStream`) with
    `graph_iter=None` + `wire_pump=False` — the mini-mux is driven
    by the parent's pump (inherited via `StreamMux._make_child`), and
    the handle never pulls upstream itself. Pump-driving methods
    delegate to the parent pump so `handle.output` and friends drive
    the root run.

    Subclasses set the parent pump function captured at construction
    (`_parent_pump_fn` / `_parent_apump_fn`) and override
    `_pump_next` / `_apump_next` to delegate to it.

    Status is updated in place by `SubgraphTransformer`. Iterate
    `run.subgraphs` to receive handles as subgraphs spawn, then
    drill into projections inside the loop body **before** the next
    pump cycle — same lazy-subscribe constraint as root projections.
    """
    path: tuple[str, ...]
    graph_name: str | None
    trigger_call_id: str | None
    status: SubgraphStatus
    error: str | None
    _seen_terminal: bool
    ...


class SubgraphRunStream(GraphRunStream, _SubgraphRunStreamMixin):
    """Sync handle for a discovered subgraph (extends `GraphRunStream`)."""
    def __init__(self, mux: StreamMux, *, path: tuple[str, ...], graph_name: str | None = ..., trigger_call_id: str | None = ...) -> None:
        ...
    


class AsyncSubgraphRunStream(AsyncGraphRunStream, _SubgraphRunStreamMixin):
    """Async handle for a discovered subgraph (extends `AsyncGraphRunStream`)."""
    def __init__(self, mux: StreamMux, *, path: tuple[str, ...], graph_name: str | None = ..., trigger_call_id: str | None = ...) -> None:
        ...
    


