"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Iterator
from typing import Generic, TYPE_CHECKING, TypeVar

if TYPE_CHECKING:
    ...
T = TypeVar("T")
class StreamChannel(Generic[T]):
    """Single-consumer drainable queue for streaming events, with optional
    protocol auto-forwarding.

    When constructed with a `name`, the StreamMux auto-wires every
    `push()` to also inject a `ProtocolEvent` into the main event stream
    using the channel's name as the method. When constructed without a
    name, the channel is local-only — items are only visible to
    in-process consumers that iterate the channel directly.

    Items are popped off the front as the consumer advances — there is
    no retention beyond what's currently queued. A channel accepts
    exactly one subscriber; a second `__iter__` / `__aiter__` call
    raises. Use `tee(n)` / `atee(n)` for fan-out.

    Starts unbound — neither `__iter__` nor `__aiter__` is available
    until the StreamMux calls `_bind(is_async)`. After binding, only
    the matching iteration protocol works; the other raises `TypeError`.

    Pump wiring (set by the run stream, not by `_bind`):
        - `_request_more`: sync pump callable, returns True if a new
          event was produced.
        - `_arequest_more`: async pump coroutine factory, same contract.

    Memory is bounded by caller pace: both sync and async use caller-
    driven pumps, so each cursor advance produces at most one event.

    Lazy-subscribe: `push` appends to the local buffer only when a
    subscriber has registered. Auto-forward via `_wire_fn` always fires
    regardless of subscription state.

    Lifecycle (`close` / `fail`) is managed by the mux — transformers
    don't need to close their channels manually.
    """
    def __init__(self, name: str | None = ..., *, maxlen: int | None = ...) -> None:
        """Initialize the channel.

        Args:
            name: Optional protocol channel name. When set, the
                StreamMux wires every `push()` to also inject a
                `ProtocolEvent` into the main event stream. Surfaced
                on the wire as `custom:<name>` for user-defined
                transformers, or as `<name>` for channels owned by a
                native transformer (`_native = True`). When `None`,
                the channel is local-only.
            maxlen: Accepted for forward compatibility; currently
                unused. The caller-driven pump bounds memory naturally
                for single-consumer use.

        Raises:
            ValueError: If `maxlen` is not a positive integer or `None`.
        """
        ...
    
    def push(self, item: T) -> None:
        """Append an item. Auto-forwards if wired.

        The local buffer append is a no-op when no subscriber is
        registered, but auto-forwarding always fires so wired events
        reach the main event log regardless of subscription state.

        Items are stored as `(stamp, item)` tuples where stamp is a
        monotonic counter from the owning mux. Stamps are stripped by
        the default cursors; raw stamped tuples are visible on `_items`.

        Raises:
            RuntimeError: If the channel is closed (and subscribed).
        """
        ...
    
    def close(self) -> None:
        """Mark the channel as complete."""
        ...
    
    def fail(self, err: BaseException) -> None:
        """Mark the channel as errored.

        Args:
            err: The exception to surface to the subscriber.
        """
        ...
    
    def __iter__(self) -> Iterator[T]:
        """Subscribe and return a sync cursor. Can be called only once.

        Raises:
            TypeError: If the channel is unbound or bound to async mode.
            RuntimeError: If the channel already has a subscriber.
        """
        ...
    
    def __aiter__(self) -> AsyncIterator[T]:
        """Subscribe and return an async cursor. Can be called only once.

        Raises:
            TypeError: If the channel is unbound or bound to sync mode.
            RuntimeError: If the channel already has a subscriber.
        """
        ...
    
    def tee(self, n: int = ...) -> tuple[Iterator[T], ...]:
        """Subscribe and return `n` independent sync iterators.

        Each branch has its own buffer; items pulled from the
        underlying cursor are copied into every branch. Branches are
        naturally bounded by caller pace since the sync pump is
        caller-driven.

        Args:
            n: Number of branches to create. Must be >= 1.

        Returns:
            A tuple of `n` iterators over the same underlying stream.

        Raises:
            TypeError: If the channel is unbound or bound to async mode.
            RuntimeError: If the channel already has a subscriber.
            ValueError: If `n` < 1.
        """
        ...
    
    def atee(self, n: int = ...) -> tuple[AsyncIterator[T], ...]:
        """Subscribe and return `n` independent async iterators.

        Caller-driven fan-out: each branch's `__anext__` either pops
        from its own buffer or, under a shared `asyncio.Lock`, pulls
        one item from the underlying cursor and distributes it to
        every branch's buffer.

        Args:
            n: Number of branches to create. Must be >= 1.

        Returns:
            A tuple of `n` async iterators over the same underlying
            stream.

        Raises:
            TypeError: If the channel is unbound or bound to sync mode.
            RuntimeError: If the channel already has a subscriber.
            ValueError: If `n` < 1.
        """
        ...
    


