"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Iterable, Mapping
from typing import Any
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import BaseCheckpointSaver, Checkpoint
from langgraph.channels.base import BaseChannel
from langgraph.managed.base import ManagedValueMapping, ManagedValueSpec

LATEST_VERSION = ...
GetNextVersion = Callable[[Any, None], Any]
def empty_checkpoint() -> Checkpoint:
    ...

def exit_delta_task_id(step: int, task_id: str) -> str:
    """Synthetic task id for exit-mode DeltaChannel writes.

    Embeds the superstep in the first UUID group so `ORDER BY task_id, idx`
    preserves chronological order while remaining a valid RFC UUID (required by
    Postgres `checkpoint_writes.task_id uuid` columns).
    """
    ...

def delta_channels_to_snapshot(channels: Mapping[str, BaseChannel], counters_since_delta_snapshot: Mapping[str, tuple[int, int]]) -> set[str]:
    """Return the set of DeltaChannel names that should snapshot now.

    A channel snapshots when EITHER its accumulated update count reaches
    `snapshot_frequency` OR the total supersteps since its last snapshot
    reaches `DELTA_MAX_SUPERSTEPS_SINCE_SNAPSHOT`. This is a pure
    predicate — no mutation.
    """
    ...

def get_updated_channels_from_tasks(run_tasks: Iterable[Any]) -> set[str]:
    """Channel names written by an update_state superstep (excluding PUSH)."""
    ...

def get_delta_channels_from_all_channels(channels: Mapping[str, BaseChannel]) -> set[str]:
    """DeltaChannels to snapshot on the first update_state of a fresh thread."""
    ...

def create_metadata_for_update_state_api(channels: Mapping[str, BaseChannel], updated_channels: set[str], *, prev_metadata: Mapping[str, Any] | None) -> dict[str, tuple[int, int]]:
    """Advance ``counters_since_delta_snapshot`` for update_state on a non-fresh thread.

    Mirrors the per-superstep counter bump in ``_loop._put_checkpoint``.
    """
    ...

def create_checkpoint_plan_for_update_state_api(channels: Mapping[str, BaseChannel], updated_channels: set[str], *, step: int, parents: dict[str, Any], saved_metadata: Mapping[str, Any] | None, is_fresh_thread: bool) -> tuple[set[str], dict[str, Any]]:
    """Return ``(channels_to_snapshot, metadata)`` for an update_state head."""
    ...

def create_checkpoint(checkpoint: Checkpoint, channels: Mapping[str, BaseChannel] | None, step: int, *, id: str | None = ..., updated_channels: set[str] | None = ..., get_next_version: GetNextVersion | None = ..., channels_to_snapshot: set[str] | None = ...) -> Checkpoint:
    """Build a new Checkpoint from the previous one and live channel state.

    For each name in `channels_to_snapshot`, a `_DeltaSnapshot(value)` blob
    is written into `channel_values[k]`. Other delta channels are omitted
    from `channel_values` — the ancestor walk reconstructs their state
    from `checkpoint_writes`. Callers compute the set via
    `delta_channels_to_snapshot(channels, counters)`; defaults to empty
    (no snapshots) when not provided.
    """
    ...

def channels_from_checkpoint(specs: Mapping[str, BaseChannel | ManagedValueSpec], checkpoint: Checkpoint, *, saver: BaseCheckpointSaver | None = ..., config: RunnableConfig | None = ...) -> tuple[Mapping[str, BaseChannel], ManagedValueMapping]:
    """Hydrate channels from a checkpoint.

    For most channels, `spec.from_checkpoint(checkpoint["channel_values"][k])`
    is sufficient. `DeltaChannel` is the exception: when the channel is
    absent from `channel_values`, an ancestor walk via
    `saver.get_delta_channel_history` is required to find the nearest seed
    (`_DeltaSnapshot` blob or pre-migration plain value) and accumulate
    the writes between it and the target. All delta channels needing
    replay are batched into a single saver call.
    """
    ...

async def achannels_from_checkpoint(specs: Mapping[str, BaseChannel | ManagedValueSpec], checkpoint: Checkpoint, *, saver: BaseCheckpointSaver | None = ..., config: RunnableConfig | None = ...) -> tuple[Mapping[str, BaseChannel], ManagedValueMapping]:
    """Async version of `channels_from_checkpoint`. See docstring there."""
    ...

def copy_checkpoint(checkpoint: Checkpoint) -> Checkpoint:
    ...

