"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, NamedTuple
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.runnables import RunnableConfig
from langgraph.types import PregelExecutableTask, RetryPolicy

logger = ...
SUPPORTS_EXC_NOTES = ...
SUPPORTS_TASK_CANCELLING = ...
@dataclass(frozen=True, slots=True)
class _ResolvedTimeout:
    run_timeout_secs: float | None
    idle_timeout_secs: float | None
    refresh_on: Literal["auto", "heartbeat"] | None
    ...


class _AttemptContext(NamedTuple):
    """Immutable per-attempt metadata shared across start/progress/finish events.

    Built once at attempt start and referenced (not copied) by every emitted
    `_AttemptEvent`, so per-event allocation is just the small event wrapper.

    Intentionally underscore-prefixed: this and `_AttemptEvent` are part of an
    internal observer contract consumed by langgraph-server. Do not move to
    `langgraph.types` — server imports them by this path.
    """
    task_id: str
    task_name: str
    attempt: int
    run_id: str | None
    thread_id: str | None
    checkpoint_ns: str | None
    started_at: datetime
    run_timeout_secs: float | None
    idle_timeout_secs: float | None
    refresh_on: Literal["auto", "heartbeat"] | None
    ...


@dataclass(frozen=True, slots=True)
class _AttemptEvent:
    """One lifecycle event for a timed attempt.

    Holds a reference to the shared `_AttemptContext` and the event-specific
    fields. The observer must treat this and `context` as read-only — they
    are reused across all events for the same attempt.
    """
    context: _AttemptContext
    event: Literal["start", "progress", "finish"]
    progress_at: datetime | None = ...
    finished_at: datetime | None = ...
    status: Literal["success", "error"] | None = ...
    error_type: str | None = ...
    error_message: str | None = ...


class _TimedAttemptScope:
    """Guarded-config window for timed attempts.

    The wrapped config marks writes, stream events, runtime stream writer calls,
    child task scheduling, and any LangChain callback event emitted under the
    node's run as observable progress when `refresh_on="auto"`.
    `runtime.heartbeat()` exposes a manual progress signal for work that doesn't
    otherwise emit any of these, and is the only progress signal when
    `refresh_on="heartbeat"`.
    Guarded writes are serialized with `close()` so cancelled background tasks
    cannot persist writes past the timeout boundary. Stream/custom output is
    best-effort: it is dropped after close is observed, but callbacks run outside
    the lock because they may contain arbitrary user/runtime code.
    """
    __slots__ = ...
    def __init__(self, on_progress: Callable[[], None] | None = ..., progress_min_interval: float = ..., refresh_on: Literal["auto", "heartbeat"] | None = ...) -> None:
        ...
    
    def wrap_config(self, config: RunnableConfig) -> RunnableConfig:
        ...
    
    def touch(self) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    async def wait_for_idle_timeout(self, idle_timeout_s: float) -> None:
        ...
    


class _IdleProgressCallbackHandler(BaseCallbackHandler):
    """Resets the idle timeout clock on any LangChain callback event.

    Inherits via `config["callbacks"]`, so it sees only events emitted by
    runs descended from the node's attempt — sibling nodes do not bleed
    through. Holds the scope by weakref so a child manager that outlives
    the attempt cannot keep the scope alive.
    """
    run_inline = ...
    def __init__(self, scope: _TimedAttemptScope) -> None:
        ...
    
    on_llm_start = ...
    on_chat_model_start = ...
    on_llm_new_token = ...
    on_llm_end = ...
    on_llm_error = ...
    on_chain_start = ...
    on_chain_end = ...
    on_chain_error = ...
    on_tool_start = ...
    on_tool_end = ...
    on_tool_error = ...
    on_retriever_start = ...
    on_retriever_end = ...
    on_retriever_error = ...
    on_agent_action = ...
    on_agent_finish = ...
    on_text = ...
    on_retry = ...
    on_custom_event = ...


def run_with_retry(task: PregelExecutableTask, retry_policy: Sequence[RetryPolicy] | None, configurable: dict[str, Any] | None = ...) -> None:
    """Run a task with retries."""
    ...

async def arun_with_retry(task: PregelExecutableTask, retry_policy: Sequence[RetryPolicy] | None, stream: bool = ..., match_cached_writes: Callable[[], Awaitable[Sequence[PregelExecutableTask]]] | None = ..., configurable: dict[str, Any] | None = ...) -> None:
    """Run a task asynchronously with retries."""
    ...

