"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Callable, Iterator
from contextvars import ContextVar
from typing import Any, TypeVar
from uuid import UUID
from langchain_core.callbacks import BaseCallbackHandler
from langgraph.pregel.protocol import StreamChunk
from langchain_core.tracers._streaming import _StreamingCallbackHandler

T = TypeVar("T")
ToolCallWriter = Callable[[Any], None]
_tool_call_writer: ContextVar[ToolCallWriter | None] = ...
class StreamToolCallHandler(BaseCallbackHandler, _StreamingCallbackHandler):
    """Callback handler that emits tool-call lifecycle events on the stream.

    Fires on LangChain's `on_tool_*` callbacks and pushes to the `tools`
    stream mode. Emits `tool-started` / `tool-output-delta` /
    `tool-finished` / `tool-error` payloads keyed by `tool_call_id`.

    While a tool is executing, this handler sets `_tool_call_writer` to a
    closure bound to that call's namespace and `tool_call_id`.
    `ToolRuntime.emit_output_delta` reads that ContextVar so tool bodies
    can stream partial output without threading the writer through their
    own signature.

    Attached by `Pregel.stream` / `astream` when `"tools"` is in
    `stream_modes`. `run_inline = True` keeps event ordering
    deterministic.
    """
    run_inline = ...
    def __init__(self, stream: Callable[[StreamChunk], None], subgraphs: bool, *, parent_ns: tuple[str, ...] | None = ...) -> None:
        """Configure the handler to stream tool-call events.

        Args:
            stream: Callable that accepts a `StreamChunk` tuple
                `(namespace, mode, payload)` and enqueues it.
            subgraphs: Whether to emit events from tools called inside
                nested subgraphs. When False, only tools at the
                handler's own scope (`parent_ns`) emit.
            parent_ns: Namespace where the handler was attached.
                Mirrors the `StreamMessagesHandler` escape hatch:
                tools whose containing namespace equals `parent_ns`
                still emit even with `subgraphs=False`, so a node that
                explicitly streams a subgraph with `stream_mode="tools"`
                sees its own tools.
        """
        ...
    
    def tap_output_aiter(self, run_id: UUID, output: AsyncIterator[T]) -> AsyncIterator[T]:
        """Pass-through — required by the `_StreamingCallbackHandler` protocol."""
        ...
    
    def tap_output_iter(self, run_id: UUID, output: Iterator[T]) -> Iterator[T]:
        """Pass-through — sync counterpart to `tap_output_aiter`."""
        ...
    
    def on_tool_start(self, serialized: dict[str, Any], input_str: str, *, run_id: UUID, parent_run_id: UUID | None = ..., tags: list[str] | None = ..., metadata: dict[str, Any] | None = ..., inputs: dict[str, Any] | None = ..., **kwargs: Any) -> Any:
        ...
    
    def on_tool_end(self, output: Any, *, run_id: UUID, parent_run_id: UUID | None = ..., **kwargs: Any) -> Any:
        ...
    
    def on_tool_error(self, error: BaseException, *, run_id: UUID, parent_run_id: UUID | None = ..., **kwargs: Any) -> Any:
        ...
    


